### PR TITLE
Add support for wbcatalog source

### PR DESCRIPTION
**Pull request by danielfdsilva**

### CODE REVIEW

**Comment by danielfdsilva** [comment]
Base structure for the WB catalog integration.

Still todo:
- [ ] Integrate with the catalog endpoint to index resources
- [ ] Get the data from the catalog when creating a scenario

These depend on some changes needed on the catalog. See https://github.com/WorldBank-Transport/ram-backend/issues/214

**Comment by olafveerman** [comment]
This can be tested with:

tag: ram-rn
https://datacatalog.worldbank.org/dataset/roads-gambia

tag: ram-admin
https://datacatalog.worldbank.org/dataset/rwanda-admin-boundaries-and-villages

@danielfdsilva

**Comment by olafveerman** [comment]
@danielfdsilva Please rebase this branch with develop. Had to force update it to purge the bu config files.

**Comment by danielfdsilva** [comment]
@olafveerman I think we should implement this https://github.com/WorldBank-Transport/ram-backend/issues/225 to finish this feature, but it should be ready to test.

**Comment by danielfdsilva** [comment]
@olafveerman There was another PR open #234 that merged into this one and fixed a couple of issues. I fast-forwarded this branch and now should be all good

**Pull request merged**
